import Header from '@/components/Header'
import Sidebar from '@/components/Sidebar'
import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>Althrun Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className='flex bg-gray-100' >
        {/* Left Sidebar */}
        <Sidebar></Sidebar>
        {/* Feed(creat post and posts) */}
        {/* Right Sidebar */}
      </main>
    </>
  )
}
