import Feed from "@/components/Feed";
import Header from "@/components/Header";
import Login from "@/components/Login";
import Sidebar from "@/components/Sidebar";
import { getSession } from "next-auth/react";
import Head from "next/head";

export default function Home({ session }) {
  if (!session) return <Login></Login>;

  return (
    <>
      <Head>
        <title>Althrun Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className="flex bg-gray-100">
        {/* Left Sidebar */}
        <Sidebar></Sidebar>
        {/* Feed(creat post and posts) */}
        <Feed></Feed>
        {/* Right Sidebar */}
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: { session },
  };
}
